# Generated by Django 5.1.5 on 2025-04-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(db_column='InvoiceID', primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(db_column='CustomerID')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=10)),
                ('parcel_detail', models.TextField(db_column='ParcelDetail')),
                ('date', models.DateField(db_column='Date')),
            ],
            options={
                'db_table': 'invoicetable',
                'permissions': [('can_add_invoice', 'Can Add Invoice')],
                'managed': False,
            },
        ),
    ]
